name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: setup buildozer
      uses: ArtemSBulgakov/buildozer-action@master
      with:
        command: buildozer android debug
        workdir: school_management_android
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: SchoolManagementApp
        path: school_management_android/bin/*.apk
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: school_management_android/bin/*.apk
